version: '3.8'

x-shared:
  &common
    NEO4J_AUTH: neo4j/test
    NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    NEO4JLABS_PLUGINS: '["apoc"]'
    NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"

x-shared-cluster:
  &common-cluster
    <<: *common
    NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
    NEO4J_dbms_memory_pagecache_size: 100M
    NEO4J_dbms_memory_heap_initial__size: 100M
    NEO4J_causal__clustering_discovery__listen__address: 0.0.0.0:5000
    NEO4J_causal__clustering_transaction__listen__address: 0.0.0.0:6000
    NEO4J_causal__clustering_raft__listen__address: 0.0.0.0:7000

x-shared-core:
  &common-core
    <<: *common-cluster
    NEO4J_dbms_mode: CORE
    NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3

networks:
    neo4j:
        driver: bridge

services:
    neo4j:
        networks:
            - neo4j
        image: neo4j:4.4-enterprise
        healthcheck:
            test: "wget -q --method=HEAD http://localhost:7474 || exit 1"
            interval: 30s
            timeout: 10s
            retries: 5
        ports:
            - "7687:7687"
            - "7474:7474"
        environment:
            <<: *common
        volumes:
            - ./tests/resources:/import
        env_file:
            - .env
